---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  minReadySeconds: 5
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      db: mysql 
      ver: "5.7.41"    
  template: 
    metadata: 
      name: mysql-db 
      labels:
        db: mysql 
        ver: "5.7.41"
    spec:
      volumes:
        - persistentVolumeClaim:
            claimName: mysql-pvc
          name: 'mysql-vol'  
      containers:
        - image: mysql:5.7.41
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP 
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol     
          env: 
            - name: MYSQL_USER
              value: mysql-user  
            - name: MYSQL_PASSWORD
              value: mysql-password 
            - name: MYSQL_DATABASE
              value: mysql-db
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot      
          readinessProbe:
            timeoutSeconds: 5
            periodSeconds: 5



---
apiVersion: v1 
kind: Service
metadata:
  name: mysql-svc
spec: 
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: mysql-port
  selector:
    db: mysql 
    ver: "5.7.41"                                       
