---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-db-deployment
spec:
  minReadySeconds: 2
  replicas: 2
  selector: 
    matchLabels: 
      db: mysql
      ver: "5.7.41"
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 30%
      maxUnavailable: 30%
  template: 
    metadata:
      name: db
      labels:
        db: mysql
        ver: "5.7.41" 
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc   
      containers: 
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: db
            - name: MYSQL_USER   
              value: user
            - name: MYSQL_PASSWORD  
              value: password 
          image: mysql:5.7.41
          name: mysql-db
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          readinessProbe:
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 1
            successThreshold: 1
            failureThreshold: 1
            tcpSocket:
              host:
              port: 3306    