---
apiVersion: v1 
kind: Service
metadata:
  name: mysql-svc
spec: 
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: mysql-port
  selector:
    db: mysql 
    ver: "5.7.41"   