apiVersion: v1
kind: Namespace
metadata:
  name: dev-namespace
spec:


---
apiVersion: v1
kind: Namespace
metadata:
  name: qa-namespace
spec:


---
apiVersion: v1
kind: Namespace
metadata:
  name: uat-namespace
spec:

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-namespace
spec: